name       : sqlite3
version    : 3.15.2
release    : 12
source     :
    - http://www.sqlite.org/2016/sqlite-autoconf-3150200.tar.gz : 07b35063b9386865b78226cdaca9a299d938a87aaa8fdc4d73edb0cef30f3149
license    :
    - Public-Domain
summary    : Self contained SQL package
description: |
    The SQLite package is a software library that implements a self-contained, serverless, zero-configuration, transactional SQL database engine.
optimize   : speed
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
component  : system.base
emul32     : yes
setup      : |
    ex_opts=""
    if [[ -z "${EMUL32BUILD}" ]]; then
        ex_opts="--enable-readline"
    fi

    %configure --prefix=/usr --disable-static $ex_opts \
            CFLAGS="$CFLAGS -DSQLITE_ENABLE_FTS3=1 \
            -DSQLITE_ENABLE_COLUMN_METADATA=1     \
            -DSQLITE_ENABLE_UNLOCK_NOTIFY=1       \
            -DSQLITE_ENABLE_DBSTAT_VTAB=1         \
            -DSQLITE_SECURE_DELETE=1"
build      : |
    %make
install    : |
    %make_install
