name       : sqlite3
version    : 3.16.2
release    : 13
source     :
    - https://sqlite.org/2017/sqlite-autoconf-3160200.tar.gz : 65cc0c3e9366f50c0679c5ccd31432cea894bc4a3e8947dabab88c8693263615
license    : Public-Domain
summary    : Self contained SQL package
description: |
    The SQLite package is a software library that implements a self-contained, serverless, zero-configuration, transactional SQL database engine.
optimize   : speed
component  : system.base
emul32     : yes
setup      : |
    ex_opts=""
    if [[ -z "${EMUL32BUILD}" ]]; then
        ex_opts="--enable-readline"
    fi

    %configure --prefix=/usr --disable-static $ex_opts \
            CFLAGS="$CFLAGS -DSQLITE_ENABLE_FTS3=1 \
            -DSQLITE_ENABLE_COLUMN_METADATA=1     \
            -DSQLITE_ENABLE_UNLOCK_NOTIFY=1       \
            -DSQLITE_ENABLE_DBSTAT_VTAB=1         \
            -DSQLITE_SECURE_DELETE=1"
build      : |
    %make
install    : |
    %make_install
