name       : sqlite3
version    : 3.25.3
release    : 28
source     :
    - https://www.sqlite.org/2018/sqlite-autoconf-3250300.tar.gz : 00ebf97be13928941940cc71de3d67e9f852698233cd98ce2d178fd08092f3dd
license    : Public-Domain
component  : system.base
optimize   : speed
emul32     : yes
summary    : Self contained SQL package
description: |
    The SQLite package is a software library that implements a self-contained, serverless, zero-configuration, transactional SQL database engine.
setup      : |
    ex_opts=""
    if [[ -z "${EMUL32BUILD}" ]]; then
        ex_opts="--enable-readline"
    fi

    %configure --disable-static \
        --enable-dynamic-extensions \
        --enable-fts5 \
        --enable-threadsafe \
        $ex_opts \
        CFLAGS="$CFLAGS \
        -DSQLITE_ENABLE_FTS3 \
        -DSQLITE_ENABLE_FTS4 \
        -DSQLITE_ENABLE_FTS5 \
        -DSQLITE_ENABLE_JSON1 \
        -DSQLITE_ENABLE_COLUMN_METADATA \
        -DSQLITE_ENABLE_UNLOCK_NOTIFY \
        -DSQLITE_ENABLE_DBSTAT_VTAB \
        -DSQLITE_SECURE_DELETE \
        -DSQLITE_ENABLE_FTS3_PARENTHESIS"
build      : |
    %make
install    : |
    %make_install
    install -D -m00644 sqlite3.1 $installdir/usr/share/man/man1/sqlite3.1
