name       : sqlite3
version    : 3.20.1
release    : 19
source     :
    - https://www.sqlite.org/2017/sqlite-autoconf-3200100.tar.gz : ec66595b29bc0798b023a5122021ea646ab4fa9e2f735937c5426feeba950742
license    : Public-Domain
summary    : Self contained SQL package
description: |
    The SQLite package is a software library that implements a self-contained, serverless, zero-configuration, transactional SQL database engine.
optimize   : speed
component  : system.base
emul32     : yes
setup      : |
    ex_opts=""
    if [[ -z "${EMUL32BUILD}" ]]; then
        ex_opts="--enable-readline"
    fi

    %configure --prefix=/usr \
            --disable-static \
            --enable-fts5 \
            -enable-threadsafe \
            --enable-threads-override-locks \
            --enable-load-extension \
            $ex_opts \
            CFLAGS="$CFLAGS -DSQLITE_ENABLE_FTS3=1 \
            -DSQLITE_ENABLE_COLUMN_METADATA=1     \
            -DSQLITE_ENABLE_UNLOCK_NOTIFY=1       \
            -DSQLITE_ENABLE_DBSTAT_VTAB=1         \
            -DSQLITE_SECURE_DELETE=1              \
            -DSQLITE_ENABLE_FTS3_PARENTHESIS=1    \
            -DSQLITE_ENABLE_FTS3=3"
build      : |
    %make
install    : |
    %make_install
