name        : sqlite3
version     : 3.12.1
release     : 7
source     :
    - http://www.sqlite.org/2016/sqlite-autoconf-3120100.tar.gz : 1c038519862b3983b0475f3ed3143ce4bbfcd21bfbd0741192f415838c831a7c
license     :
    - Public-Domain
summary     : Self contained SQL package
description : |
    The SQLite package is a software library that implements a self-contained, serverless, zero-configuration, transactional SQL database engine.
optimize   : speed
setup      : |
    %configure --disable-static \
            CFLAGS="$CFLAGS -DSQLITE_ENABLE_FTS3=1 \
            -DSQLITE_ENABLE_COLUMN_METADATA=1     \
            -DSQLITE_ENABLE_UNLOCK_NOTIFY=1       \
            -DSQLITE_SECURE_DELETE=1"
build      : |
    %make
install    : |
    %make_install
