name       : sqlite3
version    : 3.13.0
release    : 10
source     :
    - http://www.sqlite.org/2016/sqlite-autoconf-3130000.tar.gz : e2797026b3310c9d08bd472f6d430058c6dd139ff9d4e30289884ccd9744086b
license    :
    - Public-Domain
summary    : Self contained SQL package
description: |
    The SQLite package is a software library that implements a self-contained, serverless, zero-configuration, transactional SQL database engine.
optimize   : speed
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
emul32     : yes
setup      : |
    ex_opts=""
    if [[ -z "${EMUL32BUILD}" ]]; then
        ex_opts="--enable-readline"
    fi
    
    %configure --prefix=/usr --disable-static $ex_opts \
            CFLAGS="$CFLAGS -DSQLITE_ENABLE_FTS3=1 \
            -DSQLITE_ENABLE_COLUMN_METADATA=1     \
            -DSQLITE_ENABLE_UNLOCK_NOTIFY=1       \
            -DSQLITE_ENABLE_DBSTAT_VTAB=1         \
            -DSQLITE_SECURE_DELETE=1"
build      : |
    %make
install    : |
    %make_install
