name        : sqlite3
version     : 3.8.9.0
release     : 6
source      :
    - http://www.sqlite.org/2015/sqlite-autoconf-3080900.tar.gz : 76ebb6392cd2289fbff903af7ff67f3e49bd01ff30544b8028ecededd60269a2
homepage    : http://www.sqlite.org/
license     :
    - Public-Domain
summary     : Self contained SQL package
description : |
    The SQLite package is a software library that implements a self-contained, serverless, zero-configuration, transactional SQL database engine.
setup      : |
    %configure --disable-static \
            CFLAGS="$CFLAGS -DSQLITE_ENABLE_FTS3=1 \
            -DSQLITE_ENABLE_COLUMN_METADATA=1     \
            -DSQLITE_ENABLE_UNLOCK_NOTIFY=1       \
            -DSQLITE_SECURE_DELETE=1"
build      : |
    %make
install    : |
    %make_install
