name       : sqlite3
version    : 3.19.2
release    : 17
source     :
    - https://www.sqlite.org/2017/sqlite-autoconf-3190200.tar.gz : ca5361fb01cc3ad63d6fd4eb2cb0b6398e629595896d3558f7e121d37dac2ffc
license    : Public-Domain
summary    : Self contained SQL package
description: |
    The SQLite package is a software library that implements a self-contained, serverless, zero-configuration, transactional SQL database engine.
optimize   : speed
component  : system.base
emul32     : yes
setup      : |
    ex_opts=""
    if [[ -z "${EMUL32BUILD}" ]]; then
        ex_opts="--enable-readline"
    fi

    %configure --prefix=/usr --disable-static $ex_opts \
            CFLAGS="$CFLAGS -DSQLITE_ENABLE_FTS3=1 \
            -DSQLITE_ENABLE_COLUMN_METADATA=1     \
            -DSQLITE_ENABLE_UNLOCK_NOTIFY=1       \
            -DSQLITE_ENABLE_DBSTAT_VTAB=1         \
            -DSQLITE_SECURE_DELETE=1"
build      : |
    %make
install    : |
    %make_install
