name       : sqlite3
version    : 3.22.0
release    : 21
source     :
    - https://www.sqlite.org/2018/sqlite-autoconf-3220000.tar.gz : 2824ab1238b706bc66127320afbdffb096361130e23291f26928a027b885c612
license    : Public-Domain
component  : system.base
optimize   : speed
emul32     : yes
summary    : Self contained SQL package
description: |
    The SQLite package is a software library that implements a self-contained,
    serverless, zero-configuration, transactional SQL database engine.
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2018-8740.patch

    ex_opts=""
    if [[ -z "${EMUL32BUILD}" ]]; then
        ex_opts="--enable-readline"
    fi

    %configure --disable-static \
        --enable-fts5 \
        --enable-threadsafe \
        $ex_opts \
        CFLAGS="$CFLAGS \
        -DSQLITE_ENABLE_FTS3 \
        -DSQLITE_ENABLE_FTS4 \
        -DSQLITE_ENABLE_FTS5 \
        -DSQLITE_ENABLE_COLUMN_METADATA \
        -DSQLITE_ENABLE_UNLOCK_NOTIFY \
        -DSQLITE_ENABLE_DBSTAT_VTAB \
        -DSQLITE_SECURE_DELETE \
        -DSQLITE_ENABLE_FTS3_PARENTHESIS"
build      : |
    %make
install    : |
    %make_install
    install -D -m0644 sqlite3.1 $installdir/usr/share/man/man1/sqlite3.1
