name       : sqlite3
version    : 3.19.0
release    : 16
source     :
    - https://www.sqlite.org/2017/sqlite-autoconf-3190000.tar.gz : b516e665952c6659638eab3283f09f317afb212fd8e39d6415b4b6259c37b0f5
license    : Public-Domain
summary    : Self contained SQL package
description: |
    The SQLite package is a software library that implements a self-contained, serverless, zero-configuration, transactional SQL database engine.
optimize   : speed
component  : system.base
emul32     : yes
setup      : |
    ex_opts=""
    if [[ -z "${EMUL32BUILD}" ]]; then
        ex_opts="--enable-readline"
    fi

    %configure --prefix=/usr --disable-static $ex_opts \
            CFLAGS="$CFLAGS -DSQLITE_ENABLE_FTS3=1 \
            -DSQLITE_ENABLE_COLUMN_METADATA=1     \
            -DSQLITE_ENABLE_UNLOCK_NOTIFY=1       \
            -DSQLITE_ENABLE_DBSTAT_VTAB=1         \
            -DSQLITE_SECURE_DELETE=1"
build      : |
    %make
install    : |
    %make_install
